
-------------------------------------------
-- FORMATEAMOS LOS VALORES DE LOS SALDOS
SELECT 
SALDO,
REPLACE (SALDO, '.', ','),
TO_NUMBER(REPLACE (SALDO, '.', ','))
FROM TMP_DEUDACLIENTE D

--------------------------------------------
-- SUMATORIA DE LOS SALDOS DE LAS DEUDAS PARA UN MES
SELECT 
SUM(TO_NUMBER (REPLACE (SALDO, '.', ',')))
FROM TMP_DEUDACLIENTE
WHERE PERIODO = 201601



---------------------------------


SELECT * FROM TMP_PERSONA

--- creamos la tabla en el esquema operacional 
CREATE TABLE MAE_PERSONA 
(
NumDoc VARCHAR2(50),
DigVer VARCHAR2(50),
GrpVot VARCHAR2(50),
Ubigeo VARCHAR2(50),
ApPaterno VARCHAR2(50),
ApMaterno VARCHAR2(50),
Nombres VARCHAR2(50),
FecNacimiento DATE,
Sexo VARCHAR2(50)
)



insert into MAE_PERSONA(
NUMDOC,
DIGVER,
GRPVOT,
UBIGEO,
APPATERNO,
APMATERNO,
NOMBRES,
FECNACIMIENTO,
SEXO
)
select
NUMDOC,
DIGVER,
GRPVOT,
UBIGEO,
APPATERNO,
APMATERNO,
NOMBRES,
TO_DATE (FECNAC,'YYYYMMDD'),
SEXO
from tmp_persona;

COMMIT;

SELECT DISTINCT SEXO from tmp_persona;

SELECT SEXO, COUNT(*) from tmp_persona
GROUP BY SEXO

SELECT * from tmp_persona
WHERE TRIM(SEXO) IS NULL


SELECT * from tmp_persona
WHERE TRIM(SEXO) IS NULL


SELECT GRPVOT, COUNT(*) from tmp_persona
GROUP BY GRPVOT 

SELECT LENGTH(GRPVOT) , COUNT(*) from tmp_persona
GROUP BY LENGTH(GRPVOT)

SELECT * from tmp_persona
WHERE LENGTH(GRPVOT) = 10

-------------------------
--ALT 1 -> IMPUTAR VALOR CON NULO
SELECT 
CASE WHEN GRPVOT ='PARCHE EQX' THEN NULL
ELSE GRPVOT
END,
GRPVOT
from tmp_persona
WHERE
LENGTH(GRPVOT) = 10

---
-- ALT 2: VALIDAR OWNER




19641021
YYYYMMDD
------------------------------------

SELECT DISTINCT TIPO FROM TMP_ENTIDADES

SELECT MIN(TIPO), MAX(TIPO) FROM TMP_ENTIDADES

----------------------------------
SELECT MIN(COD_SBS_CLI), MAX(COD_SBS_CLI) FROM TMP_DEUDACLIENTE


SELECT 
MIN(LENGTH(TO_NUMBER(COD_SBS_CLI))), 
MAX(LENGTH(TO_NUMBER(COD_SBS_CLI)))
FROM TMP_DEUDACLIENTE


SELECT *
FROM TMP_DEUDACLIENTE
WHERE 
LENGTH(COD_SBS_CLI) = 4

----------------------------------------------------------

SELECT 
SALDO,
REPLACE(SALDO, '.', ',' )AS SALDO_FORMATO_REPLACE,
TO_NUMBER(REPLACE(SALDO, '.', ',' )) AS SALDO_FORMATO_REPLACE_TONUMBER,
A.*
FROM 
TMP_DEUDACLIENTE A
WHERE 
COD_SBS_CLI = '4448'


---

SELECT 
'12,324.00' ,
(REPLACE ('12,324.00', ',', NULL)),
REPLACE (REPLACE ('12,324.00', ',', NULL), '.', ',')
FROM DUAL
 

-- SUMAREMOS EL SALDO

SELECT 
COD_SBS_CLI ,
--SUM(TO_NUMBER(SALDO))
SUM(REPLACE(SALDO, '.', ',' )),
SUM(TO_NUMBER(REPLACE(SALDO, '.', ',' )))
FROM 
TMP_DEUDACLIENTE A
WHERE 
COD_SBS_CLI = '4448'
GROUP BY 
COD_SBS_CLI


--------------

SELECT 
COD_SBS_CLI ,
COD_CUENTA,
TIP_CREDITO,
SITCRE,
CASE WHEN SUBSTR(SITCRE, 4,1) IN ('1','3','4','5','6') AND 
          SUBSTR(COD_CUENTA, 1, 2) = '14' AND
          TIP_CREDITO = '10' THEN 'Prestamo Pequeña Empresa'
  ELSE 'OTROS'
  END CAMPO,
--SUM(TO_NUMBER(REPLACE(SALDO, '.', ',' )))
TO_NUMBER(REPLACE(SALDO, '.', ',' ))
FROM 
TMP_DEUDACLIENTE A
WHERE 
SUBSTR(COD_CUENTA, 1, 2) = '14'
AND TIP_CREDITO = '10'
SUBSTR(SITCRE, 4,1) IN ('1','3','4','5','6')


ORDER BY CAMPO DESC

COD_SBS_CLI = '4448'


---------------------------------------------------------------
-- CALIDA DE DATOS
---------------------------------------------------------------




SELECT * FROM
TMP_DEUDACLIENTE;

--- CREACION DE LA TABLA PERFILAMIENTO 
DROP TABLE PERFILAMIENTO_DATOS

CREATE TABLE PERFILAMIENTO_DATOS(
PERIODO CHAR(6),
ENTIDAD VARCHAR2(50),
ATRIBUTO VARCHAR2(50),
LONGITUD_MAXIMA INT,
LONGITUD_MINIMA INT,
VALOR_MAXIMO INT,
VALOR_MINIMO INT,
SUMATORIA NUMBER,
PROMEDIO DECIMAL (14,2),
CTD_REGISTROS_ENTIDAD INT,
CTD_REGISTROS_CAMPO INT,
PORCENTAJE_NULOS DECIMAL (6,2),
FECHA_ACTUALIZACION DATE
)

SELECT 
PERIODO, COUNT(*)
FROM
TMP_DEUDACLIENTE
GROUP BY PERIODO;


INSERT INTO PERFILAMIENTO_DATOS
SELECT 
PERIODO,
'TMP_DEUDACLIENTE' AS ENTIDAD,
'SALDO' AS ATRIBUTO,
MAX(LENGTH(SALDO)),
MIN(LENGTH(SALDO)),
MAX(TO_NUMBER(REPLACE(SALDO, '.', ',' ))) MAXIMO,
MIN(TO_NUMBER(REPLACE(SALDO, '.', ',' ))) MINIMO,
SUM(TO_NUMBER(REPLACE(SALDO, '.', ',' ))) SUMATORIA,
ROUND(AVG(TO_NUMBER(REPLACE(SALDO, '.', ',' ))), 2) AS "PROMEDIO",
COUNT(*),
COUNT(SALDO),
(1 - (COUNT(SALDO) / COUNT(*))) * 100 AS "PORCENTAJE NULOS",
SYSDATE
FROM
TMP_DEUDACLIENTE
GROUP BY PERIODO 
UNION
SELECT 
PERIODO,
'TMP_DEUDACLIENTE' AS ENTIDAD,
'TIP_REG' AS ATRIBUTO,
MAX(LENGTH(TIP_REG)),
MIN(LENGTH(TIP_REG)),
MAX(TO_NUMBER(REPLACE(TIP_REG, '.', ',' ))) MAXIMO,
MIN(TO_NUMBER(REPLACE(TIP_REG, '.', ',' ))) MINIMO,
SUM(TO_NUMBER(REPLACE(TIP_REG, '.', ',' ))) SUMATORIA,
ROUND(AVG(TO_NUMBER(REPLACE(TIP_REG, '.', ',' ))), 2) AS "PROMEDIO",
COUNT(*),
COUNT(TIP_REG),
(1 - (COUNT(TIP_REG) / COUNT(*))) * 100 AS "PORCENTAJE NULOS",
SYSDATE
FROM
TMP_DEUDACLIENTE
GROUP BY PERIODO 
UNION
SELECT 
PERIODO,
'TMP_DEUDACLIENTE' AS ENTIDAD,
'TIP_CREDITO' AS ATRIBUTO,
MAX(LENGTH(TIP_CREDITO)),
MIN(LENGTH(TIP_CREDITO)),
MAX(TO_NUMBER(REPLACE(TIP_CREDITO, '.', ',' ))) MAXIMO,
MIN(TO_NUMBER(REPLACE(TIP_CREDITO, '.', ',' ))) MINIMO,
SUM(TO_NUMBER(REPLACE(TIP_CREDITO, '.', ',' ))) SUMATORIA,
ROUND(AVG(TO_NUMBER(REPLACE(TIP_CREDITO, '.', ',' ))), 2) AS "PROMEDIO",
COUNT(*),
COUNT(TIP_CREDITO),
(1 - (COUNT(TIP_CREDITO) / COUNT(*))) * 100 AS "PORCENTAJE NULOS",
SYSDATE
FROM
TMP_DEUDACLIENTE
GROUP BY PERIODO ;

COMMIT;

SELECT * FROM PERFILAMIENTO_DATOS;


------------------------------------------------
------------------------------------------------
-- PERSONAS

SELECT
NUMDOC,
SYSDATE,
FECNAC,
TO_DATE(FECNAC,'YYYYMMDD'),
MONTHS_BETWEEN( TRUNC(SYSDATE), TO_DATE(FECNAC,'YYYYMMDD')) MESES,
MONTHS_BETWEEN( TRUNC(SYSDATE), TO_DATE(FECNAC,'YYYYMMDD')) / 12 AÑOS,
FLOOR(MONTHS_BETWEEN( TRUNC(SYSDATE), TO_DATE(FECNAC,'YYYYMMDD')) / 12) EDAD
FROM 
TMP_PERSONA


SELECT a.*,( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) -  TO_NUMBER(TO_CHAR(FECNAC,'YYYYMMDD') ) ) / 10000 AS Edad_decimal,
 TRUNC( ( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) -  TO_NUMBER(TO_CHAR(FECNAC,'YYYYMMDD') ) ) / 10000) AS Edad
FROM TMP_PERSONA a
WHERE NUMDOC = '15336570'


select 
TRUNC(months_between(TRUNC(sysdate),MPE_FECNAC)/12)
as EDAD 
from TMP_PERSONA;


------

SELECT 
A.*, ROUND(MONTHS_BETWEEN(SYSDATE, TO_DATE(FECNAC,'YYYYMMDD'))/12,0) EDAD 
FROM TMP_PERSONA  A;  

19601208


------------------------------------------------
------------------------------------------------
-- 
SELECT * FROM TMP_UBIGEO


